### ISSUE TITLE
Bricked T4

### ISSUE THREAD

**Issue by rootorben** [friendlyarm/sd-fuse_rk3399#4]
I know, this is not the right place for my issue......
but I do not know where else I could get rid of that .....

Last year I took my nanopc-t4 and I would like to bring it back to life ....

the thing is, I currently have no real pc to work .... only a latte panda 4gb 64gb ...... but that would actually work but I think so, right? #windows10

had prepared a sd card with oreo with win32 disk imager, but hdmi gives no signal! danch I've tried it via the android tool (type-c), but that does not work either.... 

here are the photos

![1](https://user-images.githubusercontent.com/45014600/66269942-cb744a80-e84e-11e9-8a7f-f33f1b0a0ba2.PNG)
![2](https://user-images.githubusercontent.com/45014600/66269943-cb744a80-e84e-11e9-9924-afe03649cb10.PNG)
![3](https://user-images.githubusercontent.com/45014600/66269944-cb744a80-e84e-11e9-94ed-8813486c26f8.PNG)
![4](https://user-images.githubusercontent.com/45014600/66269945-cc0ce100-e84e-11e9-8681-ee03bd7430a2.PNG)
![5](https://user-images.githubusercontent.com/45014600/66269946-cc0ce100-e84e-11e9-911a-0d8215551278.PNG)
![6](https://user-images.githubusercontent.com/45014600/66269947-cca57780-e84e-11e9-9a2a-d81324fc3b6b.PNG)

so i think my last option would be to connect the pins, right? #shortcircuit

could somebody please tell me how 2 do this type of shit?

I do not know which pins exactly, nor the time, or the procedure ......

Thanks alot!

**Comment by friendlyarm** [comment]
Please send an email to techsupport@friendlyarm.com
