### ISSUE TITLE
Can't get kernel v4.19 source

### ISSUE THREAD

**Issue by ichitodake** [friendlyarm/sd-fuse_rk3399#6]
In kernel-4.19 branch
> ./build-kernel.sh friendlycore-focal-arm64
Cloning into '/tmp/sd-fuse_rk3399/out/kernel-rk3399'...
warning: Could not find remote branch nanopi4-linux-v4.19.y to clone.
fatal: Remote branch nanopi4-linux-v4.19.y not found in upstream origin

It seems that there is not nanopi4-linux-v4.19.y branch in https://github.com/friendlyarm/kernel-rockchip repo yet.
Where can I get the bsp kernel v4.19 source for nanopi m4?

**Comment by friendlyarm** [comment]
Hi,

v4.19 has been pushed
https://github.com/friendlyarm/kernel-rockchip/tree/nanopi4-v4.19.y
