### ISSUE TITLE
rk_3399_V2启动失败

### ISSUE THREAD

**Issue by liu19971111** [friendlyarm/sd-fuse_rk3399#7]
**rockchip-dmc dmc: Failed to get leakage
rockchip-dmc dmc: Failed to get pvtm
rockchip-dmc dmc: could not find power_model node**
编译后在V2版本的板子上启动不了屏幕也是花的，但是在第一代板子上是可以的，是板子的问题吗
代码git clone 下来没做过更改。

**Comment by friendlyarm** [comment]
这几行日志没有负面影响，或者说与您描述的问题没有直接联系。
建议先使用我们发布的最新rom测试，如果存在异常，请收集详细的日志并描述问题，联系技术支持。
