### ISSUE TITLE
friendlycore focal内核什么时候能升级到5.x版本？

### ISSUE THREAD

**Issue by programmejava** [friendlyarm/sd-fuse_rk3399#8]
现在内核无法运行wireguard。

**Comment by friendlyarm** [comment]
为支持GPU/VPU/Camera等，现阶段friendlycore focal采用rockchip提供的4.19内核

**Comment by cjwddtc** [comment]
那有没有绕过方案呢？比如dkms？官方是不是可以提供一下dkms，让我们可以手动编译内核模块呢？

**Comment by friendlyarm** [comment]
已经支持 5.x内核，参考readme checkout到相关分支即可
